=== SafetyCulture/api-json-schemas/schemas/audit.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://api.safetyculture.io/schemas/audit.json",
  "title": "iAuditor Audit API",
  "type": "object",
  "required": [
    "template_id",
    "audit_id",
    "created_at",
    "modified_at",
    "audit_data",
    "template_data",
    "header_items",
    "items"
  ],
  "properties": {
    "template_id": {
      "$ref": "definitions.json#/template_id"
    },
    "audit_id": {
      "$ref": "definitions.json#/audit_id"
    },
    "archived": {
      "type": "boolean"
    },
    "created_at": {
      "title": "",
      "description": "",
      "type": "string",
      "format": "date-time"
    },
    "modified_at": {
      "title": "",
      "description": "",
      "type": "string",
      "format": "date-time"
    },
    "audit_data": {
      "title": "",
      "description": "",
      "$ref": "#/definitions/audit_data"
    },
    "template_data": {
      "title": "",
      "description": "",
      "$ref": "#/definitions/template_data"
    },
    "header_items": {
      "title": "",
      "description": "",
      "type": "array",
      "items": {
        "$ref": "#/definitions/audit_item"
      }
    },
    "items": {
      "title": "",
      "description": "",
      "type": "array",
      "items": {
        "$ref": "#/definitions/audit_item"
      }
    }
  },
  "definitions": {
    "audit_data": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "score": {
          "type": "number"
        },
        "total_score": {
          "type": "number"
        },
        "score_percentage": {
          "type": "number"
        },
        "duration": {
          "type": "number"
        },
        "date_modified": {
          "type": "string",
          "format": "date-time"
        },
        "date_started": {
          "type": "string",
          "format": "date-time"
        },
        "date_completed": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "authorship": {
          "$ref": "#/definitions/authorship"
        },
        "location": {
          "$ref": "#/definitions/location"
        }
      }
    },
    "template_data": {
      "type": "object",
      "properties": {
        "authorship": {
          "$ref": "#/definitions/authorship"
        },
        "response_sets": {
          "$ref": "definitions.json#/response_sets"
        },
        "metadata": {
          "type": "object",
          "description": "Template metadata",
          "properties": {
            "name": {
              "type": "string",
              "description": "The display and report name of the template"
            },
            "description": {
              "type": "string",
              "description": "Description of the template"
            },
            "image": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "$ref": "#/definitions/media_item"
                }
              ]
            }
          }
        }
      }
    },
    "authorship": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "device_id": {
          "type": "string"
        }
      }
    },
    "location": {
      "type": "object",
      "properties": {
        "started": {
          "type": "object",
          "properties": {
            "accuracy": {
              "type": "number"
            },
            "geometry": {
              "$ref": "geometry.json#"
            }
          }
        },
        "completed": {
          "type": "object",
          "properties": {
            "accuracy": {
              "type": "number"
            },
            "geometry": {
              "$ref": "geometry.json#"
            }
          }
        }
      }
    },
    "media_item": {
      "type": "object",
      "required": [
        "media_id"
      ],
      "properties": {
        "date_created": {
          "type": "string",
          "format": "date-time"
        },
        "file_ext": {
          "type": "string"
        },
        "media_id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "href": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "audit_item": {
      "allOf": [
        {
          "$ref": "definitions.json#/template_audit_item"
        }
      ],
      "required": [
        "label",
        "item_id",
        "type"
      ],
      "properties": {
        "options": {},
        "label": {
          "type": "string"
        },
        "item_id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "parent_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "responses": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "value": {
              "type": [
                "string",
                "number"
              ]
            },
            "name": {
              "type": "string"
            },
            "timestamp": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "datetime": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "location": {
              "type": "object",
              "properties": {
                "iso_country_code": {
                  "type": "string"
                },
                "administrative_area": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "thoroughfare": {
                  "type": "string"
                },
                "locality": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "sub_administrative_area": {
                  "type": "string"
                },
                "postal_code": {
                  "type": "string"
                },
                "formatted_address": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "sub_locality": {
                  "type": "string"
                },
                "sub_thoroughfare": {
                  "type": "string"
                },
                "geometry": {
                  "$ref": "geometry.json#"
                }
              }
            },
            "location_text": {
              "type": "string"
            },
            "selected": {
              "type": "array",
              "items": {
                "$ref": "definitions.json#/response_set_response"
              }
            },
            "weather": {
              "$ref": "definitions.json#/weather_response"
            },
            "assets": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "media": {
          "type": "array",
          "items": {
            "$ref": "definitions.json#/media_item"
          }
        },
        "inactive": {
          "type": "boolean"
        },
        "evaluation": {
          "type": "boolean"
        },
        "children": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "scoring": {
          "type": "object",
          "properties": {
            "score": {
              "type": "number"
            },
            "max_score": {
              "type": "number"
            },
            "score_percentage": {
              "type": "number"
            },
            "combined_score": {
              "type": "number"
            },
            "combined_max_score": {
              "type": "number"
            },
            "combined_score_percentage": {
              "type": "number"
            }
          }
        }
      }
    }
  }
}

=== SafetyCulture/api-json-schemas/schemas/__tests__/fixtures/pass/weather.json
{
  "created_at": "2015-06-26T11:47:30.083Z",
  "modified_at": "2015-06-26T11:47:30.083Z",
  "archived": false,
  "audit_data": {
    "score": 0,
    "date_completed": "2015-06-26T11:47:19.000Z",
    "name": "Android items audit",
    "date_modified": "2015-06-26T11:43:31.000Z",
    "duration": 171,
    "authorship": {
      "owner": "Rowan Smith",
      "device_id": "a14e354cfe188fc6",
      "author": "Rowan Smith"
    },
    "date_started": "2015-06-26T11:44:28.000Z",
    "total_score": 0
  },
  "items": [
    {
      "responses": {},
      "item_id": "66c7e83b-868b-4a4b-9f89-51229683669a",
      "label": "Assets",
      "type": "section",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      },
      "children": [
        "01ee347f-370d-4882-910c-dfa0564f2916",
        "28695cfe-f04d-4cc4-b735-8d4870724d46",
        "032e8efc-a00c-4ad4-862f-874a8ee8e645"
      ]
    },
    {
      "parent_id": "66c7e83b-868b-4a4b-9f89-51229683669a",
      "responses": {},
      "item_id": "01ee347f-370d-4882-910c-dfa0564f2916",
      "label": "Asset selected",
      "type": "asset",
      "options": {
        "weighting": 1,
        "locked": false,
        "is_mandatory": false,
        "assets": [
          "ff6d3195-bb3f-42df-ba0a-0a9e973438b5"
        ],
        "multiple_selection": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "66c7e83b-868b-4a4b-9f89-51229683669a",
      "responses": {},
      "item_id": "28695cfe-f04d-4cc4-b735-8d4870724d46",
      "label": "Multi assets select",
      "type": "asset",
      "options": {
        "weighting": 1,
        "locked": false,
        "is_mandatory": false,
        "assets": [
          "ff6d3195-bb3f-42df-ba0a-0a9e973438b5",
          "360a8f5b-f3be-4e51-8b1b-5c359d583ad4"
        ],
        "multiple_selection": true
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "66c7e83b-868b-4a4b-9f89-51229683669a",
      "responses": {},
      "item_id": "032e8efc-a00c-4ad4-862f-874a8ee8e645",
      "label": "None selected",
      "type": "asset",
      "options": {
        "weighting": 1,
        "locked": false,
        "is_mandatory": false,
        "multiple_selection": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "responses": {},
      "item_id": "da1aa8e4-18b1-4c1f-8a6b-44d067edbe0e",
      "label": "weather",
      "type": "section",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      },
      "children": [
        "36b19c58-9f33-4fb4-9d76-ce2880b8d608",
        "5a077d1e-58ad-41d8-bd37-7d535a4e5cda",
        "596aaa3b-33f6-4999-9f18-1e0f8bf0f509"
      ]
    },
    {
      "parent_id": "da1aa8e4-18b1-4c1f-8a6b-44d067edbe0e",
      "responses": {},
      "item_id": "36b19c58-9f33-4fb4-9d76-ce2880b8d608",
      "label": "Weather set",
      "type": "weather",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "da1aa8e4-18b1-4c1f-8a6b-44d067edbe0e",
      "responses": {},
      "item_id": "5a077d1e-58ad-41d8-bd37-7d535a4e5cda",
      "label": "Weather manual?",
      "type": "weather",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "da1aa8e4-18b1-4c1f-8a6b-44d067edbe0e",
      "responses": {},
      "item_id": "596aaa3b-33f6-4999-9f18-1e0f8bf0f509",
      "label": "Weather not set",
      "type": "weather",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "responses": {},
      "item_id": "5286cfb1-dbcd-4bae-94a9-096aff169191",
      "label": "barcode",
      "type": "section",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      },
      "children": [
        "6974149c-bb19-4d55-9839-54a194b764c1",
        "a4f9b2a4-5319-41ac-9bcd-88fc8cd6644b",
        "4ae8aa0f-6b4f-443a-b6e4-277c23238d24"
      ]
    },
    {
      "parent_id": "5286cfb1-dbcd-4bae-94a9-096aff169191",
      "responses": {
        "timestamp": "2015-06-26T11:46:29.000Z",
        "text": "9780136042594"
      },
      "item_id": "6974149c-bb19-4d55-9839-54a194b764c1",
      "label": "Selected",
      "type": "scanner",
      "options": {
        "hide_barcode": false,
        "is_mandatory": false,
        "weighting": 1
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "5286cfb1-dbcd-4bae-94a9-096aff169191",
      "responses": {
        "timestamp": "2015-06-26T11:47:09.000Z",
        "text": "9780937073803"
      },
      "item_id": "a4f9b2a4-5319-41ac-9bcd-88fc8cd6644b",
      "label": "Selected, value hidden",
      "type": "scanner",
      "options": {
        "hide_barcode": true,
        "is_mandatory": false,
        "weighting": 1
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "5286cfb1-dbcd-4bae-94a9-096aff169191",
      "responses": {},
      "item_id": "4ae8aa0f-6b4f-443a-b6e4-277c23238d24",
      "label": "Not selected",
      "type": "scanner",
      "options": {
        "hide_barcode": false,
        "is_mandatory": false,
        "weighting": 1
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    }
  ],
  "audit_id": "audit_e1db2267028145478097944867f3e21e",
  "template_data": {
    "authorship": {
      "owner": "Rowan Smith",
      "date_created": "2015-06-26T11:37:19.000Z",
      "author": "Rowan Smith",
      "device_id": "a14e354cfe188fc6",
      "date_modified": "2015-06-26T11:44:02.000Z"
    },
    "metadata": {
      "image": "",
      "description": "Pewpewpew",
      "name": "Android items"
    }
  },
  "header_items": [
    {
      "responses": {},
      "item_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "label": "Title Page",
      "type": "section",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      },
      "children": [
        "f3245d46-ea77-11e1-aff1-0800200c9a66",
        "f3245d40-ea77-11e1-aff1-0800200c9a66",
        "f3245d41-ea77-11e1-aff1-0800200c9a66",
        "f3245d42-ea77-11e1-aff1-0800200c9a66",
        "f3245d43-ea77-11e1-aff1-0800200c9a66",
        "f3245d44-ea77-11e1-aff1-0800200c9a66",
        "f3245d45-ea77-11e1-aff1-0800200c9a66"
      ]
    },
    {
      "parent_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "responses": {
        "text": "000001"
      },
      "item_id": "f3245d46-ea77-11e1-aff1-0800200c9a66",
      "label": "Document No.",
      "type": "textsingle",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "responses": {
        "text": "Android items audit"
      },
      "item_id": "f3245d40-ea77-11e1-aff1-0800200c9a66",
      "label": "Audit Title",
      "type": "textsingle",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "responses": {
        "text": "Sc"
      },
      "item_id": "f3245d41-ea77-11e1-aff1-0800200c9a66",
      "label": "Client / Site",
      "type": "textsingle",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "responses": {
        "datetime": "2015-06-26T11:44:28.000Z"
      },
      "item_id": "f3245d42-ea77-11e1-aff1-0800200c9a66",
      "label": "Conducted on",
      "type": "datetime",
      "options": {
        "enable_time": true,
        "weighting": 1,
        "is_mandatory": false,
        "enable_date": true
      },
      "scoring": {
        "score": 0,
        "max_score": 0,
        "combined_score": 0,
        "combined_max_score": 0
      }
    },
    {
      "parent_id": "e869e60e-b3fb-434e-bc7a-18d0987e70bb",
      "responses": {
        "text": "Rowan Smith"
      },
      "item_id": "f3245d43-ea77-11e1-aff1-0800200c9a66",
      "label": "Prepared by",
      "type": "textsingle",
      "options": {
        "weighting": 1,
        "is_mandatory": false
      },
      "scoring": {
